Godeltech.Mastery.Web.DigitalLibrary/Controllers/BookCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Godeltech.Mastery.Web.DigitalLibrary.Controllers
{
    public class BookCartController : Controller
    {
        // GET: BookCart
        public ActionResult Index()
        {
            return View();
        }
    }
}

Godeltech.Mastery.Web.DigitalLibrary/Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Godeltech.Mastery.Web.DigitalLibrary.Models;
using Godeltech.Mastery.Web.DigitalLibrary.Models.ViewModels;

namespace Godeltech.Mastery.Web.DigitalLibrary.Controllers
{
    public class MailController : Controller
    {
        // GET: Mail
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ClientMail()
        {
            return PartialView();
        }

        public async Task<ActionResult> SendClientMail(ClientMailViewModel client, bool isAttach)
        {
            //var adress = "white.orchid.st@gmail.com";
            //var mailTo = new string[] { adress };
            //return await SendMail(customer, isAttach, GetGmailClient, adress, mailTo);
            return View();
        }
    } 
}

Godeltech.Mastery.Web.DigitalLibrary/Views/BookCart/CartProducts.cshtml
@model application.Models.Cart

<div id="cart-table">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <table  class="table table-striped">
        <thead>
            <tr>
                <th>Picture</th>
                <th>Product name</th>
                <th>
                    <div style="margin-left:38px;">
                        Count
                    </div>
                </th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @{
                int i = 0;
            }
            @foreach (var item in Model.GetItems())
            {
                string idProdQuantity = "productQuantity" + i;
                <tr>
                    <td>
                        <div class="cart-picture">
                            <img src="@Url.Action("GetImage","Product", new { productId =item.Product.ProductsID})"/>
                        </div>
                    </td>
                    <td>
                        @item.Product.Name
                    </td>
                    <td>
                        @{string idForm = "updateForm" + i;}
                        @using (Ajax.BeginForm("UpdateCart", "Cart",
                            new
                            {
                                prodQuantityId = idProdQuantity,
                                prodIndex = i
                            },
                            new AjaxOptions
                            {
                                UpdateTargetId = "cart-table"
                            },
                            new { @id = idForm }))
                        {
                            <div class="form-group">
                                <div class="form-inline">
                                    @{ string submitBtn = "submitBtn" + i;}
                                    <a onclick="reduceValue('@idProdQuantity','@submitBtn')" class="btn btn-default fa fa-minus"></a>
                                    @Html.TextBox(idProdQuantity, item.Quantity, new
                               {
                                   @ondurationchange = "updateCart('" + idForm + "')",
                                   @class = "form-control",
                                   @style = "width:40px"
                               })
                                    <a onclick="addValue('@idProdQuantity','@submitBtn')" class="btn btn-default fa fa-plus"></a>
                                    <button style="display:none;" id="@submitBtn" type="submit" class="btn btn-default fa fa-plus"/>
                                </div>
                            </div>
                        }
                    </td>
                    <td>
                        @item.Product.Price
                    </td>
                    <td>
                        @{
                            string removeLink = "removeLink" + i;
                            int productId = Model.Items[i].Product.ProductsID;
                         }
                        <a onclick="ajaxRemoveItem('@productId')" id="@removeLink" class="btn btn-danger fa fa-close"></a>
                    </td>
                </tr>
                i++;
            }

            
            <tr>
                <th colspan="2">Total</th>
                <th>@Model.GetTotalCount()</th>
                <th colspan="2">@Model.GetTotalCost()</th>
            </tr>
        </tbody>
    </table>
    @Html.Action("OrderMail","Mail")

</div>
<script type="text/javascript">
    function ajaxRemoveItem(prodId) {
        $('#cart-table').load('@Url.Action("RemoveItem", "Cart")?prodId=' + prodId);
        $('#onlyCart').load('@Url.Action("CartSummary", "Cart")');
    }
</script>

Godeltech.Mastery.Web.DigitalLibrary/Views/BookCart/CartSummary.cshtml
@model application.Models.Cart
    <div id="cart" class="cart">
        <a href="@Url.Action("Index","Cart",new {returnUrl=Request.Path})">
            @Model.GetTotalCost() $ (@Model.GetItems().Sum(i => i.Quantity))
            <span class="glyphicon glyphicon-shopping-cart"></span>
        </a>
    </div>

Godeltech.Mastery.Web.DigitalLibrary/Views/BookCart/Index.cshtml
@model application.Models.Cart

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div id="cart-body">
        <h2 class="cart-label">Your cart</h2>
        @if (Model != null&&Model.Items.Count>0)
        {
            @Html.Partial("CartProducts",Model)
            <div class="form-group">
                <a href="@TempData["returnUrl"]" class="btn btn-primary">Return</a>
            </div>
        }
        else
        {
            <div class="jumbotron">
                Cart is empty
            </div>
            <a href="@Url.Action("Index","Home")" class="btn btn-primary">Return</a>
        }
    </div>
</div>

@Styles.Render("~/Content/cart.css")
@section scripts
{
    <script type="text/javascript">
        function addValue(id, idBtn) {
            document.getElementById(id).value++;
            //document.getElementById(idForm).submit();
            var jqIdBtn = "#" + idBtn;
            $(jqIdBtn).trigger('click');
        }

        function reduceValue(id, idBtn) {
            var val = document.getElementById(id).value;
            if (val > 0) {
                document.getElementById(id).value--;
                //document.getElementById(idForm).submit();
                 //var eventObj = new CustomEvent('durationchange');
                 //document.getElementById(id).dispatchEvent(durationchange);
                var jqIdBtn = "#" + idBtn;
                $(jqIdBtn).trigger('click')
            }
        }

        function updateCart(id)
        {
           document.getElementById(id).submit()
        }
    </script>
}





   